<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; background: #f5f5f5; }
        .container { background: #fff; border-radius: 8px; padding: 30px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .header { border-bottom: 2px solid #e5e7eb; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 22px; color: #111; }
        .header .period { color: #6b7280; font-size: 14px; margin-top: 4px; }
        .section { margin-bottom: 24px; }
        .section h2 { font-size: 16px; color: #374151; margin: 0 0 10px 0; border-bottom: 1px solid #f3f4f6; padding-bottom: 6px; }
        .issue-list { list-style: none; padding: 0; margin: 0; }
        .issue-list li { padding: 8px 0; border-bottom: 1px solid #f9fafb; }
        .issue-list li:last-child { border-bottom: none; }
        .issue-number { font-weight: 600; color: #2563eb; text-decoration: none; }
        .issue-number:hover { text-decoration: underline; }
        .issue-repo { font-size: 12px; color: #9ca3af; margin-left: 6px; }
        .commit-list { list-style: none; padding: 0; margin: 0; font-size: 13px; }
        .commit-list li { padding: 5px 0; border-bottom: 1px solid #f9fafb; font-family: monospace; }
        .commit-hash { color: #6b7280; }
        .commit-repo { color: #9ca3af; font-size: 11px; }
        .footer { margin-top: 20px; text-align: center; font-size: 12px; color: #9ca3af; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Weekly Report</h1>
            <div class="period">{{ $weekStart }} &mdash; {{ $weekEnd }}</div>
        </div>

        @if(count($report['repositories'] ?? []) > 0)
        <div class="section">
            <h2>Repositories</h2>
            <p style="font-size: 14px; color: #6b7280;">{{ implode(', ', $report['repositories']) }}</p>
        </div>
        @endif

        <div class="section">
            <h2>Issues Worked On ({{ count($report['issues'] ?? []) }})</h2>
            @if(count($report['issues'] ?? []) > 0)
                <ul class="issue-list">
                    @foreach($report['issues'] as $issue)
                        <li>
                            <a href="{{ $issue['url'] ?? '#' }}" class="issue-number">#{{ $issue['number'] }}</a>
                            {{ $issue['title'] ?? '' }}
                            <span class="issue-repo">{{ $issue['repo'] ?? '' }}</span>
                        </li>
                    @endforeach
                </ul>
            @else
                <p style="color: #9ca3af; font-size: 14px;">No issues referenced this week.</p>
            @endif
        </div>

        <div class="section">
            <h2>Commits ({{ count($report['commits'] ?? []) }})</h2>
            @if(count($report['commits'] ?? []) > 0)
                <ul class="commit-list">
                    @foreach($report['commits'] as $commit)
                        <li>
                            <span class="commit-hash">{{ $commit['hash'] ?? '' }}</span>
                            {{ $commit['message'] ?? '' }}
                            <span class="commit-repo">{{ $commit['repo'] ?? '' }}</span>
                        </li>
                    @endforeach
                </ul>
            @else
                <p style="color: #9ca3af; font-size: 14px;">No commits found this week.</p>
            @endif
        </div>
    </div>

    <div class="footer">
        Generated by yxx/weekly-report
    </div>
</body>
</html>
